### ISSUE TITLE
Change README.md to specify that HUBOT_HIPCHAT_API_ENDPOINT should have a / (slash) at the end.

### ISSUE THREAD

**Issue by luciomr** [ecaron/hubot-hipchat-api#3]
Currently the documentation has the following example value for HUBOT_HIPCHAT_API_ENDPOINT: "http://my-private-hipchat.com/v2" .

In my tests the code failed to run with a similar value (replaced it with the URL of my private Hipchat server) and doing a bit of debugging I ended up noticing that it was because the value of HUBOT_HIPCHAT_API_ENDPOINT should end with a slash, like so: "http://my-private-hipchat.com/v2/"

Please change the documentation to reflect this.

**Comment by Flet** [comment]
👍 

I think a PR would be accepted!
